export { IconAvatar } from './Avatar'
export { IconBank } from './Bank'
export { IconCart } from './CartShop'
export { IconCross } from './Cross'
export { IconEyeVisible, IconEyeHidden } from './Eyes'
export { IconFavorite } from './Favorite'
export { IconFolder } from './Folder'
export { IconLike, IconDislike } from './Likes'
export { IconPlus } from './Plus'
export { IconPractice } from './Practice'
export { IconSearch } from './Search'
export { IconSmile } from './Smile'
export { IconTask } from './Task'
export { IconViewProduct } from './ViewProduct'
export { IconZero } from './Zero'
